spring.datasource.url=jdbc:postgresql://postgres:5432/todoapp
spring.datasource.username=joel
spring.datasource.password=joel_dev2025
spring.sql.init.data-locations=classpath:data-postgres.sql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.sql.init.encoding=UTF-8
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
