spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
security.jwt.secret=FJ39fj93Jf93jf93JF93jf93jf93jf93jf93jf93jf93jf9
security.jwt.expiration-ms=86400000